# Generated by Django 3.1 on 2020-09-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200903_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productman',
            name='ProductMan_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='websubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='project.category', verbose_name='Select category'),
        ),
    ]
