# Generated by Django 3.1 on 2020-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200903_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websubcategory',
            name='WebSubcategory_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
