# Generated by Django 3.1 on 2020-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200903_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websubcategory',
            name='WebSubcategory_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
