# Generated by Django 3.1 on 2020-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200903_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='inherit1',
            name='x',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
