# Generated by Django 3.1 on 2020-09-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200903_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inherit1',
            name='x',
        ),
    ]
