# Generated by Django 3.1 on 2020-09-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_inherit1_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inherit1',
            name='x',
        ),
    ]
