# Generated by Django 3.1 on 2020-09-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200903_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productman',
            options={},
        ),
        migrations.AlterModelOptions(
            name='websubcategory',
            options={},
        ),
        migrations.DeleteModel(
            name='Inherit1',
        ),
    ]
