# Generated by Django 3.1 on 2020-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200905_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productman',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='project.WebSubCategory'),
        ),
        migrations.AlterField(
            model_name='websubcategory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='project.Category'),
        ),
    ]
