# Generated by Django 3.1 on 2020-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200905_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productman',
            name='subcategory',
            field=models.CharField(max_length=50, null=True, verbose_name='project.WebSubCategory'),
        ),
    ]
