# Generated by Django 3.1 on 2020-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20200905_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMan',
        ),
        migrations.DeleteModel(
            name='WebSubCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subcateg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
